export const phoneticSpellings: Record<string, string> = {
  achieve: "/əˈtʃiːv/",
  ambiguous: "/æmˈbɪɡ.ju.əs/",
  analyze: "/ˈæn.əl.aɪz/",
  antonyms: "/ˈæn.tə.nɪmz/",
  apple: "/ˈæp.əl/",
  bad: "/bæd/",
  big: "/bɪɡ/",
  book: "/bʊk/",
  borrow: "/ˈbɑːr.oʊ/",
  bread: "/bred/",
  bus: "/bʌs/",
  car: "/kɑːr/",
  careful: "/ˈker.fəl/",
  cat: "/kæt/",
  chair: "/tʃer/",
  child: "/tʃaɪld/",
  city: "/ˈsɪt.i/",
  coherent: "/koʊˈhɪr.ənt/",
  cold: "/koʊld/",
  come: "/kʌm/",
  computer: "/kəmˈpjuː.t̬ɚ/",
  consequence: "/ˈkɑːn.sə.kwens/",
  consider: "/kənˈsɪd.ɚ/",
  consolidate: "/kənˈsɑː.lə.deɪt/",
  country: "/ˈkʌn.tri/",
  day: "/deɪ/",
  dog: "/dɔːɡ/",
  door: "/dɔːr/",
  drink: "/drɪŋk/",
  eat: "/iːt/",
  efficient: "/ɪˈfɪʃ.ənt/",
  extrapolate: "/ɪkˈstræp.ə.leɪt/",
  facilitate: "/fəˈsɪl.ə.teɪt/",
  father: "/ˈfɑː.ðɚ/",
  food: "/fuːd/",
  friend: "/frend/",
  go: "/ɡoʊ/",
  good: "/ɡʊd/",
  happy: "/ˈhæp.i/",
  hot: "/hɑːt/",
  house: "/haʊs/",
  implication: "/ˌɪm.pləˈkeɪ.ʃən/",
  improve: "/ɪmˈpruːv/",
  job: "/dʒɑːb/",
  journey: "/ˈdʒɝː.ni/",
  juxtapose: "/ˌdʒʌk.stəˈpoʊz/",
  like: "/laɪk/",
  listen: "/ˈlɪs.ən/",
  man: "/mæn/",
  milk: "/mɪlk/",
  morning: "/ˈmɔːr.nɪŋ/",
  mother: "/ˈmʌð.ɚ/",
  name: "/neɪm/",
  negotiate: "/nəˈɡoʊ.ʃi.eɪt/",
  new: "/nuː/",
  night: "/naɪt/",
  nuanced: "/ˈnuː.ɑːnst/",
  old: "/oʊld/",
  opportunity: "/ˌɑː.pɚˈtuː.nə.t̬i/",
  paradigm: "/ˈper.ə.daɪm/",
  perspective: "/pɚˈspek.tɪv/",
  phone: "/foʊn/",
  prepare: "/prɪˈper/",
  quintessential: "/ˌkwɪn.təˈsen.ʃəl/",
  read: "/riːd/",
  require: "/rɪˈkwaɪr/",
  rice: "/raɪs/",
  room: "/ruːm/",
  sad: "/sæd/",
  school: "/skuːl/",
  significant: "/sɪɡˈnɪf.ə.kənt/",
  small: "/smɔːl/",
  solution: "/səˈluː.ʃən/",
  speak: "/spiːk/",
  student: "/ˈstuː.dənt/",
  synonyms: "/ˈsɪn.ə.nɪmz/",
  support: "/səˈpɔːrt/",
  substantial: "/səbˈstæn.ʃəl/",
  table: "/ˈteɪ.bəl/",
  teacher: "/ˈtiː.tʃɚ/",
  ubiquitous: "/juːˈbɪk.wə.t̬əs/",
  usually: "/ˈjuː.ʒu.ə.li/",
  want: "/wɑːnt/",
  water: "/ˈwɑː.t̬ɚ/",
  weather: "/ˈweð.ɚ/",
  animal: "/ˈæn.ə.məl/",
  adult: "/əˈdʌlt/",
  arrive: "/əˈraɪv/",
  behavior: "/bɪˈheɪ.vjɚ/",
  cash: "/kæʃ/",
  class: "/klæs/",
  collaborate: "/kəˈlæb.ə.reɪt/",
  comprehensive: "/ˌkɑːm.prəˈhen.sɪv/",
  cool: "/kuːl/",
  contrast: "/ˈkɑːn.træst/",
  culture: "/ˈkʌl.tʃɚ/",
  decision: "/dɪˈsɪʒ.ən/",
  dislike: "/dɪsˈlaɪk/",
  doctor: "/ˈdɑːk.tɚ/",
  early: "/ˈɝː.li/",
  enemy: "/ˈen.ə.mi/",
  ephemeral: "/ɪˈfem.ɚ.əl/",
  equivocal: "/ɪˈkwɪv.ə.kəl/",
  evidence: "/ˈev.ə.dəns/",
  experience: "/ɪkˈspɪr.i.əns/",
  fresh: "/freʃ/",
  fruit: "/fruːt/",
  garden: "/ˈɡɑːr.dən/",
  hate: "/heɪt/",
  hear: "/hɪr/",
  home: "/hoʊm/",
  holiday: "/ˈhɑː.lə.deɪ/",
  hospital: "/ˈhɑː.spɪ.t̬əl/",
  huge: "/hjuːdʒ/",
  ignore: "/ɪɡˈnɔːr/",
  increase: "/ɪnˈkriːs/",
  inexorable: "/ɪnˈek.sər.ə.bəl/",
  instructor: "/ɪnˈstrʌk.tɚ/",
  intrinsic: "/ɪnˈtrɪn.zɪk/",
  large: "/lɑːrdʒ/",
  late: "/leɪt/",
  learner: "/ˈlɝː.nɚ/",
  leave: "/liːv/",
  library: "/ˈlaɪ.brer.i/",
  little: "/ˈlɪt̬.əl/",
  market: "/ˈmɑːr.kɪt/",
  message: "/ˈmes.ɪdʒ/",
  meticulous: "/məˈtɪk.jə.ləs/",
  mitigate: "/ˈmɪt.ə.ɡeɪt/",
  money: "/ˈmʌn.i/",
  music: "/ˈmjuː.zɪk/",
  opposites: "/ˈɑː.pə.zɪts/",
  park: "/pɑːrk/",
  pet: "/pet/",
  prescient: "/ˈpreʃ.ənt/",
  priority: "/praɪˈɔːr.ə.t̬i/",
  pupil: "/ˈpjuː.pəl/",
  reduce: "/rɪˈduːs/",
  reliable: "/rɪˈlaɪ.ə.bəl/",
  resilient: "/rɪˈzɪl.jənt/",
  sagacious: "/səˈɡeɪ.ʃəs/",
  skeptical: "/ˈskep.tɪ.kəl/",
  shop: "/ʃɑːp/",
  "similar words": "/ˈsɪm.ə.lɚ wɝːdz/",
  song: "/sɔːŋ/",
  stay: "/steɪ/",
  stranger: "/ˈstreɪn.dʒɚ/",
  talk: "/tɑːk/",
  temporary: "/ˈtem.pə.rer.i/",
  tiny: "/ˈtaɪ.ni/",
  warm: "/wɔːrm/",
  woman: "/ˈwʊm.ən/",
  work: "/wɝːk/",
  write: "/raɪt/",
  young: "/jʌŋ/"
};
